# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_random'),
    ]

    operations = [
        migrations.RenameField(
            model_name='random',
            old_name='name_field',
            new_name='ugabuga_field',
        ),
    ]
